auth-dispatcher {
  type = Dispatcher
  executor = "fork-join-executor"
  fork-join-executor {
    parallelism-min = 4
    parallelism-factor = 2.0
    parallelism-max = 16
  }
  throughput = 10
}

pekko.actor.deployment {
  /authRouter {
    router = smallest-mailbox-pool
    nr-of-instances = 16
    dispatcher = auth-dispatcher
  }
}
