portal-dispatcher {
  type = Dispatcher
  executor = "fork-join-executor"
  fork-join-executor {
    parallelism-min = 4
    parallelism-factor = 2.0
    parallelism-max = 16
  }
  throughput = 10
}

pekko {
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
  loglevel = "DEBUG"

  actor.deployment {
    /portalRouter {
      router = smallest-mailbox-pool
      nr-of-instances = 16
      dispatcher = portal-dispatcher
    }
    /portalRouterFailure {
      router = smallest-mailbox-pool
      nr-of-instances = 16
      dispatcher = portal-dispatcher
    }
  }
}
