pekko {
  actor {
    provider = "cluster"
    serializers {
      proto = "org.apache.pekko.remote.serialization.ProtobufSerializer"
      envelope = "game.engine.core.message.EnvelopeSerializer"
    }
    serialization-bindings {
       "com.google.protobuf.GeneratedMessageV3" = proto
       "game.engine.core.message.Envelope" = envelope
    }
  }
  remote {
    artery {
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.hostname = ${?ORION_HOST}
      canonical.port = 2551
      canonical.port = ${?ORION_PORT}
    }
  }
  cluster {
    # Seed nodes will be configured by the application
    jmx.multi-mbeans-in-same-jvm = on
  }
}
