<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>game.engine</groupId>
        <artifactId>orion-root</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>orion-player</artifactId>

    <dependencies>
        <dependency>
            <groupId>game.engine</groupId>
            <artifactId>orion-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>game.engine</groupId>
            <artifactId>orion-gateway</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
